// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8iqmOze7A4_c6WRMA9u5t1etvDaS-Cv4',
    appId: '1:1075193599725:web:bb1437ac1f1d3999651ee4',
    messagingSenderId: '1075193599725',
    projectId: 'pluto-finance-5eed2',
    authDomain: 'pluto-finance-5eed2.firebaseapp.com',
    storageBucket: 'pluto-finance-5eed2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5RBWuQ9Gmm26xU5K3feVZ_ArQoWBlihg',
    appId: '1:1075193599725:android:693162424c7cc9ab651ee4',
    messagingSenderId: '1075193599725',
    projectId: 'pluto-finance-5eed2',
    storageBucket: 'pluto-finance-5eed2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPxnfNpZSFrj5bH5QJXyd_PqBt9rcGzUY',
    appId: '1:1075193599725:ios:c50e42d81512a5ad651ee4',
    messagingSenderId: '1075193599725',
    projectId: 'pluto-finance-5eed2',
    storageBucket: 'pluto-finance-5eed2.firebasestorage.app',
    iosBundleId: 'com.example.plutoFinance',
  );
}
